-- MySQL Script generated by MySQL Workbench
-- 07/12/15 18:24:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema power_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema power_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `power_manager` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `power_manager` ;

-- -----------------------------------------------------
-- Table `power_manager`.`power_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `account_name` VARCHAR(200) NULL,
  `account_password` VARCHAR(200) NULL,
  `account_salt` INT NULL,
  `accout_type` TINYINT(10) NULL DEFAULT 5,
  `create_time` TIME NULL,
  `last_login_time` TIME NULL,
  `account_status` INT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_account_access_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_account_access_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL,
  `access_data_table` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_base_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_base_station` (
  `station_id` INT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(45) NULL,
  `station_serise_code` VARCHAR(45) NULL,
  `station_type` INT NULL,
  `station_project` VARCHAR(45) NULL,
  `station_building_type` INT NULL,
  `station_province` VARCHAR(45) NULL,
  `station_city` VARCHAR(45) NULL,
  `station_distirct` VARCHAR(45) NULL,
  `station_address` VARCHAR(200) NULL,
  `station_lat` VARCHAR(45) NULL,
  `station_lng` VARCHAR(45) NULL,
  `create_time` TIME NULL,
  `creator_id` INT NULL,
  `data_status` INT NULL,
  `project_id` INT NULL,
  PRIMARY KEY (`station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_ammeter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_ammeter` (
  `ammeter_id` INT NOT NULL AUTO_INCREMENT,
  `begin_value` INT NULL,
  `end_value` INT NULL,
  `creator_id` INT NULL,
  `create_time` TIME NULL,
  PRIMARY KEY (`ammeter_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_ammeter_chinamobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_ammeter_chinamobile` (
  `ammeter_id` INT NOT NULL AUTO_INCREMENT,
  `begin_value` INT NULL,
  `end_value` INT NULL,
  `creator_id` INT NULL,
  `create_time` TIME NULL,
  PRIMARY KEY (`ammeter_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_base_station_runing_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_base_station_runing_data` (
  `runing_data_id` INT NOT NULL AUTO_INCREMENT,
  `working_status` INT NULL,
  `device_status_1` INT NULL,
  `device_status_2` INT NULL,
  `device_status_3` INT NULL,
  `device_status_4` INT NULL,
  `device_status_5` INT NULL,
  `device_status_6` INT NULL,
  `device_status_7` INT NULL,
  `device_status_8` INT NULL,
  `device_status_fan` INT NULL,
  `device_status_cabinet` INT NULL,
  `device_status_ventilator` INT NULL,
  `station_id` INT NULL,
  `wet_inside` INT NULL,
  `wet_outside` INT NULL,
  `ammeter_normal` INT NULL,
  `ammeter_smart` INT NULL,
  `overload_ac` INT NULL,
  `overload_dc` INT NULL,
  `temperature_inside` INT NULL,
  `temperature_outside` INT NULL,
  `temperature_cabinet` INT NULL,
  `temperature_aircondition_1` INT NULL,
  `temperature_aircondition_2` INT NULL,
  `temperature_aircondition_3` INT NULL,
  `temperature_aircondition_4` INT NULL,
  `temperature_aircondition_5` INT NULL,
  `temperature_aircondition_6` INT NULL,
  `temperature_aircondition_7` INT NULL,
  `temperature_aircondition_8` INT NULL,
  `create_time` TIME NULL,
  PRIMARY KEY (`runing_data_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_base_station_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_base_station_analysis` (
  `analysis_id` INT NOT NULL AUTO_INCREMENT,
  `station_id` INT NULL,
  `device_status` INT NULL,
  `average_energy_hour` INT NULL,
  `average_energy_day` INT NULL,
  `average_energy_week` INT NULL,
  PRIMARY KEY (`analysis_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_station_warning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_station_warning` (
  `warning_id` INT NOT NULL AUTO_INCREMENT,
  `warning_type` INT NULL,
  `warning_desc` VARCHAR(500) NULL,
  `create_time` TIME NULL,
  `update_time` TIME NULL,
  `station_id` INT NULL,
  `warning_status` INT NULL,
  PRIMARY KEY (`warning_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_weather`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_weather` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `weather` VARCHAR(45) NULL,
  `temperature_high` INT NULL,
  `temperature_low` INT NULL,
  `wind` INT NULL,
  `create_time` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_base_station_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_base_station_log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `station_id` INT NULL,
  `log_type` INT NULL,
  `log_desc` VARCHAR(500) NULL,
  `origin_value` INT NULL,
  `current_value` INT NULL,
  `create_time` TIME NULL,
  `creator_id` INT NULL,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_base_station_device_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_base_station_device_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_id` INT NULL,
  `air_condition_num` INT NULL,
  `tempature_outside` INT NULL,
  `tempature_inside` INT NULL,
  `fan_out_type` VARCHAR(200) NULL,
  `fan_in_type` VARCHAR(200) NULL,
  `cabinet_num` INT NULL,
  `battery_type` VARCHAR(200) NULL,
  `battery_air_type` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_base_station_energy_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_base_station_energy_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NULL,
  `ammeter_num` INT NULL,
  `ammeter_num_chinamobile` INT NULL,
  `fee_type` VARCHAR(200) NULL,
  `power_supply_type` VARCHAR(200) NULL,
  `overload` VARCHAR(200) NULL,
  `overload_normal` VARCHAR(200) NULL,
  `sim_num` VARCHAR(200) NULL,
  `esg_num` VARCHAR(200) NULL,
  `ecu_num` VARCHAR(45) NULL,
  `power_base_station_energy_infocol` VARCHAR(200) NULL,
  `station_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`prower_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`prower_project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(200) NULL,
  `project_desc` VARCHAR(45) NULL,
  `create_time` TIME NULL,
  `creator_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `power_manager`.`power_account_access_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `power_manager`.`power_account_access_project` (
  `id` INT NOT NULL,
  `project_id` INT NULL,
  `account_id` INT NULL,
  `create_time` TIME NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
